# Generated by Django 5.0.1 on 2024-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_reviews_remove_post_image_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='upload',
            field=models.DateField(auto_now_add=True),
        ),
    ]
