# Generated by Django 5.0.1 on 2024-01-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_reviews_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
