# Generated by Django 5.0.1 on 2024-02-02 12:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
