# Generated by Django 5.0.1 on 2024-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='Designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
